import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from 'src/components/organisms'

const roboto = Roboto({ subsets: ['latin'], weight: '500' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body className={roboto.className}>
                <Header />
                {children}
            </body>
        </html>
    )
}
